name: Deploy Domain Protect
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  terraform_plan_apply_dev:
    name: Terraform plan & apply dev
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.2

      - name: checkout Domain Protect
        uses: actions/checkout@v3
        with:
          repository: ovotech/domain-protect
          ref: refs/heads/main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}
          AWS_DEPLOY_ROLE_ARN: ${{ secrets.AWS_DEPLOY_ROLE_ARN}}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform initialise
        run: >
          terraform init 
          -backend-config=bucket=${{ secrets.TERRAFORM_STATE_BUCKET}} 
          -backend-config=key=${{ secrets.TERRAFORM_STATE_KEY}} 
          -backend-config=region=${{ secrets.TERRAFORM_STATE_REGION}}

      - name: set Terraform dev workspace
        run: terraform workspace new dev || terraform workspace select dev

      - name: terraform plan dev
        run: terraform plan -out tfplan

      - name: terraform apply dev
        run: terraform apply -auto-approve tfplan